/*Minimum Smoke Emission

There are two types of vehicles available to transport people from City A to City B:

A Van can carry 100 people in one trip.
A Car can carry 4 people in one trip.

Each trip generates smoke:

A van generates Vsmoke units of smoke.
A car generates Csmoke units of smoke.

Given N people, determine the minimum total smoke generated to transport all people. You may use any combination of vans and cars. Every person must be transported, and the total smoke should be minimized by considering all possible combinations.

Input Format
The first line contains an integer T, the number of test cases.
Each of the next T lines contains three space-separated integers:
N – Number of people
Vsmoke – Smoke generated by one van trip
Csmoke – Smoke generated by one car trip
Output Format

For each test case, print the minimum smoke generated.

Constraints
1 ≤ T ≤ 100
1 ≤ N ≤ 1000
1 ≤ Vsmoke ≤ 1000
1 ≤ Csmoke ≤ 1000
Sample Input
3
60 60 23
23 40 10
105 40 20
Sample Output
60
40
80
Explanation

Test Case 1

15 cars → 15 × 23 = 345 smoke
1 van → 60 smoke

Minimum smoke = 60

Test Case 2

6 cars → 6 × 10 = 60 smoke
1 van → 40 smoke

Minimum smoke = 40

Test Case 3

27 cars → 540 smoke
1 van + 2 cars → 40 + 40 = 80 smoke
2 vans → 80 smoke

Minimum smoke = 80

Note: The solution must consider all possible numbers of vans and compute the minimum number of cars needed for the remaining people. The answer is the minimum smoke among all such combinations.*/
#include<iostream>
#include<climits>
using namespace std;
int main(){
    int tc=0;
    cin>>tc;
    int N[tc],vsmoke[tc],csmoke[tc];
    for(int i=0;i<tc;i++){
    cin>>N[i]>>vsmoke[i]>>csmoke[i];
    }
    int minsmoke=INT_MAX;
    int csmokee=0;
    for(int i=0;i<tc;i++)
    {
        int vanc=ceil(N[i]/100);
    for(int curvanc=0;curvanc<=vanc;curvanc++)
        {
        int remaing=N[i]-(curvanc*100);
        if(remaing<0){remaing=0;}
        int curc=ceil(remaing/4);
        csmokee=(curvanc*vsmoke[i])+(curc*csmoke[i]);
            if(csmokee<minsmoke)
                {
                    minsmoke=csmokee;
                }
        //cout<<"VAN: "<<curvanc<<" CAR: "<<curc<<" Smoke: "<<csmokee<<" MinSmoke: "<<minsmoke<<"\n\n";      
            }  
            cout<<minsmoke<<" ";
            minsmoke=INT_MAX;
        }
        
    }
